### PR TITLE
Issue 11

### LINKED ISSUE #11: Wrong Java package directory for org.gradle.demo.HelloServlet
it should be in org/gradle/demo not com/gradle/demo

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Closes #11

### CODE REVIEW

**Comment by eriwen** [comment]
Hi @LorenzoBettini. Thank you for the PR. Since you're a first-time contributor, could you please ensure you've signed the [Gradle CLA](https://gradle.org/cla) so I can merge this PR?

**Comment by timcu** [comment]
This is the same as pull request #6 rename folder to org to match package name ;)

**Comment by LorenzoBettini** [comment]
@eriwen I've just signed the CLA

**Comment by eriwen** [comment]
Hi @LorenzoBettini. As @timcu pointed out, I foolishly asked you for a CLA on a PR I didn't realize is a duplicate :( 

Please forgive me, and know that as I compile a list of Gradle contributors to reach out to, I will count you as well.

**Comment by LorenzoBettini** [comment]
@eriwen no problem, and thanks for counting me in :)

**Pull request closed without merging**
