### PR TITLE
Update Gradle to v4.2.1

### PR DESCRIPTION
**Pull request by Dispader**
Prelimiary tests indicate this speeds up builds by 25%.

### CODE REVIEW

**Comment by Dispader** [comment]
I should be clear: that speed increase was for *initial* builds.  After plugins are installed, builds are so fast that it's hard to say.

**Comment by eriwen** [comment]
@Dispader Thank you for the PR. It seems that you're a first time contributor — awesome! Could you please sign a Gradle CLA so I can merge this PR?

**Comment by Dispader** [comment]
@eriwen Hey there, sir.  Sorry for the delay.  I believe I've signed a Gradle CLA now.  Cheers!

**Comment by eriwen** [comment]
@Dispader My turn to apologize for a terribly late follow-up. 

A bit ago I upgraded all the guides to Gradle 4.5.1 en masse, so I cannot merge this PR. 

**However:** your efforts have not been in vain! For I am planning some nice things to folks like you who have contributed to Gradle, even in small ways. 

Stay tuned... and... sorry again for not answering for so long. I'll spare you my excuses.

**Pull request closed without merging**
